### ISSUE TITLE
New dominant speakers override pinned/selected endpoints in LastN list

### ISSUE THREAD

**Issue by jienco** [jitsi/jitsi-videobridge#1520]
## Description

When using Last N and pinning/selecting specific participant(s), they are overridden by new dominant speakers.

## Current behavior

We have a custom UI with lib-jitsi-meet. In this UI we have a stage where we can have from 1 to 4 participants, and we also have a collapsible panel to view all participants in low resolution. The stage is shared between all participants, meaning they all see the same endpoints there. When a participant closes the panel and has only stage, we use LastN and selectParticipants for that client to save bandwidth and only get the video feeds that are on stage.

We achieve that by doing these two calls in lib-jitsi-meet:

```
conference.setLastN(numberOfParticipantsOnStage);
conference.selectParticipants(arrayOfStageParticipantIds);
```

This was working well for us. Now after this update (we went from Jitsi Videobridge `2.1-273-g072dd44b` to `2.1-376-g9f12bfe2`) the problem we have is as follows: Let's say that we have participants with Endpoint IDs (real example): `49d41a92, 7222785b, b13094d2, 44f76001`. Now `49d41a92` and `7222785b` are sent to the stage. `b13094d2` client is watching only stage so he calls `setLastN` with `2`, and `selectParticipants` with IDs `49d41a92,7222785b` (as shown in these client logs):

```
2020-10-21T20:04:11.264Z [modules/RTC/BridgeChannel.js] <l.sendSelectedEndpointsMessage>:  Sending selected endpoints: 49d41a92,7222785b.
Logger.js:154 2020-10-21T20:04:11.265Z [modules/RTC/BridgeChannel.js] <l.sendSetLastNMessage>:  Sending lastN=2.
```

That works well. But now `44f76001` starts talking, and he becomes dominant speaker:

```
2020-10-21T20:07:37.870Z [modules/RTC/BridgeChannel.js] <WebSocket.e.onmessage [as __zone_symbol__ON_PROPERTYmessage]>:  New dominant speaker: 44f76001.
Logger.js:154 2020-10-21T20:07:37.872Z [modules/RTC/BridgeChannel.js] <WebSocket.e.onmessage [as __zone_symbol__ON_PROPERTYmessage]>:  New forwarded endpoints: 44f76001,49d41a92
```

From that moment on, `b13094d2` sees `7222785b` as frozen. As shown in the logs, the Videobridge has now decided to forward `44f76001` and `49d41a92`, where `44f76001` has replaced `7222785b` in our original participant list. The `7222785b` Participant Connection Status changes from active to inactive for `b13094d2`. This is easy to replicate for us and happens also when there is only one participant on stage. The dominant speaker replaces the forwarded endpoints when using LastN to get an exact amount of videos, even if we have called to select specific endpoints.

Other users have also commented that the same happens when using `pinParticipant`. The pinned participant is overriden by dominant speaker.

## Expected Behavior

When using LastN and pinning one participant or selecting multiple participant(s), those participants should remain within the LastN list until the pin/select changes. New dominant speakers would not override existing participants in that list.

This would allow also to have pagination in the UI where only the visible endpoints are included in LastN, and other endpoints  video are not downloaded, reducing bandwidth and CPU usage in the client (and also server bandwidth usage).

## Possible Solution

Not sure.

# Environment details

Self-hosted deployment using Jitsi VideoBridge `2.1-376-g9f12bfe2`.

**Comment by bgrozev** [comment]
@jienco Thank for the report! I can confirm that what you describe as expected behavior is what we also expect, so what you see is indeed a bug.

I've been trying to reproduce it in unit tests without success (you can see the attempt [here](https://github.com/bgrozev/jitsi-videobridge/commit/a42f75be4ada447e52274e799e4664f0fcf3856c), so I think the flow at a higher level is going wrong (or at least different) somewhere.

Since you can succesfully reproduce it, can you please provide a log of the messages exchanged between the viewing client and the bridge? You can do that by opening the "network" tab in chrome before you load the page, then open the conference and search for "colibri". Then find the websocket connection and open the "messages" tab.
![Uploading Screenshot 2020-11-16 at 14.55.41.png…]()

**Comment by bgrozev** [comment]
Does this happen with a single bridge, or only when more than one bridge is used with Octo?

**Comment by jienco** [comment]
@bgrozev Thank you so much for your comments and for looking into this issue. We are using single bridge per conference (no Octo enabled for now).

Here is a log of the Colibri messages exchanged, from the moment the user joins until the issue is reproduced. In this test conference we had 4 endpoints: `["9fe36a03","86898926","215fa382","a77c5213"]`. The logs are taken from `a77c5213` (the last one to join). When `a77c5213` joined, `"9fe36a03","86898926"` were on stage (selected). To reproduce easier, I muted them both and unmuted `215fa382` and started talking in order to be dominant speaker (which happened at `22:15:53.542`) after which the LastN endpoints changed to be `"86898926","215fa382"`, removing `9fe36a03` (the first one in the list) from it.

```
UP - 22:15:36.274 - {"colibriClass":"PinnedEndpointChangedEvent","pinnedEndpoint":null}

UP - 22:15:36.276 - {"colibriClass":"SelectedEndpointsChangedEvent","selectedEndpoints":["9fe36a03","86898926"]}

UP - 22:15:36.284 - {"colibriClass":"LastNChangedEvent","lastN":2}

DOWN - 22:15:36.357 - {"colibriClass":"ServerHello"}

DOWN - 22:15:36.357 - {"colibriClass":"DominantSpeakerEndpointChangeEvent","dominantSpeakerEndpoint":"86898926"}

DOWN - 22:15:36.570 - {"lastNEndpoints":["9fe36a03","86898926"],"conferenceEndpoints":["9fe36a03","86898926","215fa382"],"endpointsEnteringLastN":[],"colibriClass":"LastNEndpointsChangeEvent"}

DOWN - 22:15:36.961 - {"colibriClass":"EndpointMessage","from":"215fa382","to":"","msgPayload":{"type":"stats","values":{"bitrate":{"upload":128,"download":1076,"audio":{"upload":21,"download":63},"video":{"upload":107,"download":952}},"packetLoss":{"total":2,"download":3,"upload":0},"connectionQuality":94.81481481481481,"jvbRTT":10,"maxEnabledResolution":180}}}

UP - 22:15:37.186 - {"colibriClass":"ReceiverVideoConstraint","maxFrameHeight":360}

UP - 22:15:37.189 - {"colibriClass":"SelectedEndpointsChangedEvent","selectedEndpoints":["9fe36a03","86898926"]}

UP - 22:15:37.192 - {"colibriClass":"LastNChangedEvent","lastN":-1}

DOWN - 22:15:37.623 - {"lastNEndpoints":["9fe36a03","86898926","215fa382"],"conferenceEndpoints":["9fe36a03","86898926","215fa382"],"endpointsEnteringLastN":["215fa382"],"colibriClass":"LastNEndpointsChangeEvent"}

UP - 22:15:37.827 - {"colibriClass":"ReceiverVideoConstraint","maxFrameHeight":360}

DOWN - 22:15:37.863 - {"colibriClass":"SenderVideoConstraints", "videoConstraints":{"idealHeight":180,"preferredFps":-1.0,"preferredHeight":-1}}

DOWN - 22:15:39.968 - {"colibriClass":"EndpointMessage","from":"86898926","to":"","msgPayload":{"type":"stats","values":{"bitrate":{"upload":605,"download":542,"audio":{"upload":30,"download":33},"video":{"upload":575,"download":509}},"packetLoss":{"total":1,"download":2,"upload":0},"connectionQuality":100,"jvbRTT":8,"maxEnabledResolution":360}}}

UP - 22:15:40.676 - {"colibriClass":"SelectedEndpointsChangedEvent","selectedEndpoints":["9fe36a03","86898926"]}

DOWN - 22:15:40.830 - {"colibriClass":"EndpointMessage","from":"9fe36a03","to":"","msgPayload":{"type":"stats","values":{"bitrate":{"upload":614,"download":553,"audio":{"upload":31,"download":32},"video":{"upload":583,"download":521}},"packetLoss":{"total":1,"download":1,"upload":0},"connectionQuality":100,"jvbRTT":8,"maxEnabledResolution":360}}}

UP - 22:15:41.187 - {"colibriClass":"SelectedEndpointsChangedEvent","selectedEndpoints":["9fe36a03","86898926"]}

UP - 22:15:41.191 - {"colibriClass":"LastNChangedEvent","lastN":2}

DOWN - 22:15:41.254 - {"lastNEndpoints":["9fe36a03","86898926"],"conferenceEndpoints":["9fe36a03","86898926","215fa382"],"endpointsEnteringLastN":[],"colibriClass":"LastNEndpointsChangeEvent"}

DOWN - 22:15:46.927 - {"colibriClass":"EndpointMessage","from":"215fa382","to":"","msgPayload":{"type":"stats","values":{"bitrate":{"upload":129,"download":952,"audio":{"upload":21,"download":73},"video":{"upload":108,"download":879}},"packetLoss":{"total":0,"download":0,"upload":0},"connectionQuality":95.55555555555556,"jvbRTT":9,"maxEnabledResolution":180}}}

DOWN - 22:15:49.968 - {"colibriClass":"EndpointMessage","from":"86898926","to":"","msgPayload":{"type":"stats","values":{"bitrate":{"upload":659,"download":763,"audio":{"upload":34,"download":31},"video":{"upload":625,"download":732}},"packetLoss":{"total":0,"download":0,"upload":0},"connectionQuality":100,"jvbRTT":11,"maxEnabledResolution":360}}}

DOWN - 22:15:50.830 - {"colibriClass":"EndpointMessage","from":"9fe36a03","to":"","msgPayload":{"type":"stats","values":{"bitrate":{"upload":652,"download":767,"audio":{"upload":32,"download":33},"video":{"upload":620,"download":734}},"packetLoss":{"total":0,"download":0,"upload":0},"connectionQuality":100,"jvbRTT":8,"maxEnabledResolution":360}}}

DOWN - 22:15:53.542 - {"colibriClass":"DominantSpeakerEndpointChangeEvent","dominantSpeakerEndpoint":"215fa382"}

DOWN - 22:15:53.545 - {"lastNEndpoints":["86898926","215fa382"],"conferenceEndpoints":["9fe36a03","86898926","215fa382"],"endpointsEnteringLastN":["215fa382"],"colibriClass":"LastNEndpointsChangeEvent"}

UP - 22:15:55.963 - {"colibriClass":"EndpointMessage","msgPayload":{"type":"stats","values":{"bitrate":{"upload":129,"download":962,"audio":{"upload":22,"download":34},"video":{"upload":107,"download":928}},"packetLoss":{"total":0,"download":0,"upload":0},"connectionQuality":95.55555555555556,"jvbRTT":9,"maxEnabledResolution":180}},"to":""}

DOWN - 22:15:56.924 - {"colibriClass":"EndpointMessage","from":"215fa382","to":"","msgPayload":{"type":"stats","values":{"bitrate":{"upload":134,"download":1157,"audio":{"upload":27,"download":13},"video":{"upload":107,"download":1144}},"packetLoss":{"total":0,"download":0,"upload":0},"connectionQuality":99.25925925925925,"jvbRTT":9,"maxEnabledResolution":180}}}

DOWN - 22:15:59.969 - {"colibriClass":"EndpointMessage","from":"86898926","to":"","msgPayload":{"type":"stats","values":{"bitrate":{"upload":640,"download":759,"audio":{"upload":21,"download":27},"video":{"upload":619,"download":732}},"packetLoss":{"total":0,"download":0,"upload":0},"connectionQuality":100,"jvbRTT":9,"maxEnabledResolution":360}}}

DOWN - 22:16:00.831 - {"colibriClass":"EndpointMessage","from":"9fe36a03","to":"","msgPayload":{"type":"stats","values":{"bitrate":{"upload":642,"download":761,"audio":{"upload":21,"download":29},"video":{"upload":621,"download":732}},"packetLoss":{"total":0,"download":0,"upload":0},"connectionQuality":100,"jvbRTT":8,"maxEnabledResolution":360}}}
```

**Comment by jienco** [comment]
I read your unit tests and they make sense. Given that they pass, I suspect there could be an issue in the transformation of messages from the clients. I see that the `VideoConstraintsCompatibility` class is transforming the old-way messages to the new video constraints format. The reason why I think somehow the constraints are at some point not computed correctly, is because `EndpointMultiRanker.compare` defaults to sorting by speaker rank when there is no ideal height diff.

Is there a way to run the code in debug mode using an IDE like IntelliJ? Or which debugging way you recommend?

**Comment by gpolitis** [comment]
> The reason why I think somehow the constraints are at some point not computed correctly, is because `EndpointMultiRanker.compare` defaults to sorting by speaker rank when there is no ideal height diff.

@jienco maybe we accidentally broke something recently, but here's how it should work in the example that you describe in the issue

* `49d41a92, 7222785b` have equal priority (1st and 2nd to get a share of the estimated available bandwidth)
* then `44f76001` should be 3rd, since it doesn't have its ideal height set but is the current dominant speaker

Since you're using the old messages (as we are) which go through the compatibility layer and since your client is signaling multiple selected endpoints, the compatibility later creates video constraint with the preferred height set to `-1`. When preferred height is set to `-1` the bitrate controller disables eager allocation up to 360p for on-stage participants (because in tile-view you want to see more videos, even if it's not super high quality).

**Comment by bgrozev** [comment]
@gpolitis does that mean that the described behavior is what you expect? I.e. with "A" and "B" selected, and "C" being dominant speaker the bridge forwards "C" and "A" instead of "A" and "B"?

**Comment by bgrozev** [comment]
@jienco I plugged in the workflow fromo your logs into the unit tests, still no luck.

> Is there a way to run the code in debug mode using an IDE like IntelliJ? Or which debugging way you recommend?

Yes, I use IntelliJ IDEA to run and debug the unit tests. Should be pretty straight-forward to import via the pom file.

**Comment by bgrozev** [comment]
@jienco What version of the bridge are you using? We just discovered that #1508 fixes exactly what you report.

**Comment by jienco** [comment]
That is very good news @bgrozev . We are using `2.1-376-g9f12bfe2` (latest stable release https://github.com/jitsi/jitsi-videobridge/releases/tag/stable%2Fjitsi-meet_5142) of October 24, and that commit was made on October 26.

Thank you very much for looking into this and for adding the unit tests to ensure this functionality, I really appreciate it.

When a new release is made we will update and test (in the meantime I will try to build from source to test).

**Comment by jienco** [comment]
@bgrozev After building the deb package from master (using `resources/build_deb_package.sh` with needed deps) I tested it and I can confirm this issue is fixed. Thank you very much for the excellent work you all do in the Jitsi Team!

**Comment by M0rph3v5** [comment]
shouldn't issues only be closed once fixed in a stable release? How often are new releases done? Just rebuilding from a random point at master seems a bit wild for heavy production servers built on top of jitsi.

**Comment by s-xync** [comment]
@bgrozev If you don't mind me asking, when will the next jitsi-videobridge version be released to stable. It looks like the latest version of jitsi-videobridge is still 2.1-376-g9f12bfe2-1 from October 14th and I am also facing the mentioned issue.

**Comment by bgrozev** [comment]
There's no fixed schedule for stable releases, we push to stable after a version has been running on meet.jit.si for a few days with no issues. We've been running [406-812da0a8a16ae8af0125b3dc6464dd7c91d9423c](https://github.com/jitsi/jitsi-videobridge/commit/812da0a8a16ae8af0125b3dc6464dd7c91d9423c) on meet.jit.si since last week, so unless issues arise there should be a new stable version soon.

**Comment by s-xync** [comment]
@bgrozev  Since the time I last commented, I have also gone ahead and tried out the testing version of jitsi-videobridge2 `jitsi-videobridge2/testing,now 2.1-406-g812da0a8-1 all`. In this, the `conference.selectParticipants` seems to be resolved but I still am not getting expected behavior from `conference.pinParticipant`. When I do `conference.setLastN(0)` and `conference.pinParticipant(participantId)`, The video stream stays empty. I don't have any familiarity with videobridge code. my knowledge is strictly limited to using lib-jitsi-meet. Please let me know if I am doing something wrong. Thanks.

**Comment by bgrozev** [comment]
> When I do `conference.setLastN(0)` and `conference.pinParticipant(participantId)`

Use `conference.selectParticipant(participantId)` instead

**Comment by s-xync** [comment]
Yes, I will use that as an alternative. But I was just wondering what happened to the pinParticipant function. In my application, I want one user to be pinned always and want to paginate on the remaining users and without pinParticipant, I have to use selectParticipants and have to include this one user every time which I thought could be avoided by using pinParticipant, but if pinParticipant is not coming back, I will achieve my requirements using selectParticipant and selectParticipants. 

Also, let me know if it is deprecated so that I can make changes to the lib-jitsi-meet API docs to remove the pinParticipant function.

**Comment by bgrozev** [comment]
Yes, the intention is to use `selectedParticipant` for that behavior. I'll add docs for the new signaling format later today and let you know

**Comment by bgrozev** [comment]
An important note: in order to maintain compatibillity with the default jitsi-meet client, which currently implements tile view by selecting all endpoints, I had to break this case in #1530 *when the legacy signaling is used*. I.e. the legacy signaling (as described in #1541) does not support multiple selected endpoints, and treats them as if none were selected.

To get the desired behavior with 2 selected endpoints, use the new signaling from #1541. This should be easy to adapt to by sending e.g.
```json
{
  "colibriClass": "BandwidthAllocationSettings",
  "selectedEndpoints": ["A", "B"]
}
{
  "colibriClass": "BandwidthAllocationSettings",
  "lastN": 2,
}

```

instead of  
```json
{
  "colibriClass": "SelectedEndpointsChangedEvent",
  "selectedEndpoints": ["A", "B"]
}
{
  "colibriClass": "LastNChangedEvent",
  "lastN": 2
}
```

Howeve, if you mix legacy and new signaling, the legacy behavio will be used, so all these have to be changed.

**Comment by bgrozev** [comment]
The unit tests are still there, but they've been adapted to the new API.

**Comment by jienco** [comment]
We confirmed this issue is solved in the latest stable release https://github.com/jitsi/jitsi-videobridge/releases/tag/stable%2Fjitsi-meet_5390

Thank you very much @bgrozev!
