### ISSUE TITLE
Does initial-last-n actually works?

### ISSUE THREAD

**Issue by bukharin** [jitsi/jitsi-videobridge#2083]
## Current behavior

Hi, 

I am trying to use channelLastN option to limit lastN video before datachannel connection is established:

```
channelLastN: 1
```

I see initial-last-n option in the session-accept response from the client:

```
<initial-last-n value="1" xmlns="jitsi:colibri2"/>
```

But when datachannel is established, client receives `ForwardedSources` message which indicates that JVB forwards all existing endpoints (6 in this example)

![image](https://github.com/jitsi/jitsi-videobridge/assets/3126568/5946bde3-50aa-4775-a39a-8d8a1008e1cb)

After that JVB signals about 1 forwarding endpoint as expected (may be client `ReceiverVideoConstraints` change params?)

## Expected Behavior

JVB forwards only `initial-last-n` endpoints before datachannel established. Client does not receive `ForwardedSources` message with all endpoints after datachannel connection is established

# Environment details

Reproducable on latest release of JVB + Jicofo

**Comment by bgrozev** [comment]
Do you see any jvb log messages containing "initialLastN"?

**Comment by bukharin** [comment]
@bgrozev yes, it has

```
Setting initialLastN = 1
```

Also if I try to disable sending `ReceiverVideoConstraints` message in lib-jitsi-meet. In this case I see the same behaivour. It seems that JVB always sends `ForwardedSources` message with all endpoints.

![image](https://github.com/jitsi/jitsi-videobridge/assets/3126568/efd39fc7-9557-448b-a6e6-7584149b2f39)

**Comment by bgrozev** [comment]
That's strange and I can't reproduce it. Do you use SCTP or WS for the data channel?

**Comment by bukharin** [comment]
WebSockets, the screenshots above were taken from Chrome DevTools

**Comment by bgrozev** [comment]
I think I see how this happens. The WS must have been established before the bridge received the initial-last-n from jicofo. In this case the bridge will send the initial forwarded sources message (with lastN=-1), then send the updated on (with lastN=1) once it receives initial-last-n.

I'm surprised it happens often, because the WS requires at least an extra RTT for the TCP handshake, while the initial-last-n is just a packet sent to jicofo which immediately updates the bridge via an existing connection. 

For your use case, would it work if we add a config option to the bridge setting a default initial lastN value?

**Comment by bukharin** [comment]
@bgrozev yes, you are right. It's a race condition. 

In my case I see the problem exist in 9 of 10 attempts. May be `initial-last-n`  should be a parameter when jicofo allocate user session on JVB to prevent this race condition ?

**Comment by bgrozev** [comment]
Jicofo doesn't have that information about a participant when it does the allocation. It only has the set of capabilities (i.e. just booleans) and presence. We want to avoid adding it in presence because it's broadcast to everyone. 

Longer term using SCTP where the race doesn't exist might be the best option. That's why I'm looking for some easy workaround instead of a proper solution which would require more time that we can't invest. If you control your environment and want initial-last-n=1 for everyone I'm happy to add a configurable default in the bridge.

**Comment by bukharin** [comment]
@bgrozev I'd love to have `initial-last-n` as a configurable option of JVB

**Comment by bgrozev** [comment]
It's a very simple change, so I'll assume it works. Re-open if necessary.
