### ISSUE TITLE
No entry in json files for people who join after recording has started

### ISSUE THREAD

**Issue by roidelapluie** [jitsi/jitsi-videobridge#227]
When someone joins a session which is recording, jetsi meet will not record his track in metadata.json nor endpoints.json.

**Comment by gavllew** [comment]
I have found and fixed this before, but cannot share a patch/PR until my employer sorts out licensing/contributor agreements.

The problem is that when new SSRCs are signalled over colibri, the mapping from SSRC to EndpointID is not added to the Synchronizer instance used by RecorderRtpImpl.  I made some modifications to RtpChannel.setSources() that checks whether recording is enabled, and calls synchronizer.setEndpoint() for each new SSRC.

**Comment by roidelapluie** [comment]
Okay. I hope those legal concerns will be addressed. In fot I hope the info you've given will help other developers to make a patch.

**Comment by roidelapluie** [comment]
@gavllew is #215 solving the same problem?

**Comment by gavllew** [comment]
No - it's similar, but that one's related to simulcast instead of recording.

Sorry, my description of the fix was more to help the experienced Jitsi developers, rather than expecting you to fix it yourself.  It took me a good few hours to track down the cause, and I wanted to save save the next person some time. :-)

**Comment by roidelapluie** [comment]
Yes, I was aware of that :-)

**Comment by roidelapluie** [comment]
@gavllew any news on the legal stuff that would enable you to send a PR?

**Comment by gavllew** [comment]
No, sorry.  I do re-raise it occasionally, but not much seems to happen, so I wouldn't hold my breath. :-/
