### ISSUE TITLE
Long delay before session-initiate Jingle is received

### ISSUE THREAD

**Issue by dixoncb** [jitsi/jitsi-videobridge#641]
We're working with a UWP client with JVB, using the Matrix XMPP library. After sending a Presence to the conference (including <video/> and <audio/>) we get the conference presences as we should. It takes the conference about 7-10 seconds to send us the session-initiate Jingle which allows the WebRTC connection process to start. This happens much more quickly with JitsiMeet. What do we need to do to speed up the receipt of the session-initiate?

Thank you.

**Comment by damencho** [comment]
It is hard to me to understand how you are using jvb and xmpp, as JVB has nothing to do with presences. 
But you can take a look at jitsi-meet. Open 2 or 3 tabs (2 will be in p2p but there will be a jvb link for fallback if p2p doesn't work), and there is a debug option to save logs, you can execute "APP.conference.saveLogs();", this will give you a json file with all XMPP messages exchanged using the bosh channel. 
So when the participant joins, it sends an iq to jicofo I want to enter this room: roomName and jicofo create the room if it is not created and tells the client ok, you can enter now and then the client enters the room. When there are at least two participants in the room, jicofo will invite them. Jicofo first will contact jvb to open the needed channels then it will send the jingle messages to the client using the already opened ports.
As you are mentioning Presence, I think this issue is not jvb related at all. I will close the issue for now. If you still have questions you can ask them here or write an email to the dev mailing list.

**Comment by bgrozev** [comment]
> What do we need to do to speed up the receipt of the session-initiate?

The first thing to do would be to figure out why the delay occurs. Jicofo will enter the MUC as a regular occupant (after receiving a request from a client on it's xmpp account), it will then wait until there are at least 2 participants in the room, and then it will initiate jingle sessions.

**Comment by dixoncb** [comment]
Thank you for this. The issue was indeed as you say. When the session is created, each JVC occupant gets a disco#info request from the other occupants, and responding to the first of these triggers the session-initiate immediately. There's obviously the danger of disco request flooding, so we're aiming to implement caching as per XEP-0115. Thanks for your attention. All going well now.
