### ISSUE TITLE
Adaptive streaming feature for video bridge

### ISSUE THREAD

**Issue by soq2000** [jitsi/jitsi-videobridge#655]
Dear all, 
I just jump into this project. So very sorry for my naïve question. I would like to know if video bridge supports adaptive streaming, so that the stream received by a client will be adapted to his / her actual bandwidth ?
By the way, would you please show me the module / code segment of video bridge receiving all media streams and forwarding them to all connected participants.
Many thanks

**Comment by gpolitis** [comment]
Yes the JVB supports adaptive streaming. There are a couple of components that work together in order to provide this functionality. We have bandwidth estimations implemented in libjitsi ( you can search for RemoteBitrateEstimatorAbsTime.java and SendSideBandwidthEstimation.java). The bandwidth estimations are then used to compute the target bitrate for each individual forwarded stream. This is done in the JVB in BitrateController.java. Selectively dropping packets and rewriting the forwarded stream is done in SimulcastController.java. Please let us know if you have any further questions!
